services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: aichat-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 630wujiayuwy
      MYSQL_DATABASE: aiChat
    ports:
      - '3306:3306'
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - aichat-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: aichat-redis-dev
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - aichat-network

  # 后端应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aichat-app-dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      # 开发模式：挂载源代码，支持热重载
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=630wujiayuwy
      - DB_DATABASE=aiChat
      - redis_server_host=redis
      - redis_server_port=6379
      - redis_server_db=0
    depends_on:
      - mysql
      - redis
    networks:
      - aichat-network
    command: ["pnpm", "run", "start:dev"]

volumes:
  mysql_data_dev:
  redis_data_dev:

networks:
  aichat-network:
    driver: bridge